In [ ]:
import numpy as np

In [3]:
lst = [1, 2, 3, 4]
print(lst)

[1, 2, 3, 4]


In [7]:
print('1D Aaray')
a = np.array([(1, 2, 3), (4, 5, 6)])
print (a)

1D Aaray
[[1 2 3]
 [4 5 6]]


In [8]:
type (a)

numpy.ndarray

In [9]:
print(a.size)

6


In [10]:
print(a.shape)

(2, 3)


In [11]:
print(a.dtype)

int64


In [13]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])