In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
np.random.random(1)

array([0.38270746])

In [3]:
np.random.random((2,2))

array([[0.83818315, 0.0394829 ],
       [0.57491786, 0.00904484]])

In [7]:
np.random.randint(1,10)

4

In [9]:
np.random.randint(1,10, (3,4,5))

array([[[3, 4, 9, 5, 8],
        [1, 8, 4, 3, 4],
        [5, 1, 6, 2, 4],
        [9, 7, 7, 8, 5]],

       [[5, 2, 5, 6, 1],
        [8, 6, 8, 4, 3],
        [1, 7, 8, 4, 5],
        [4, 7, 5, 2, 1]],

       [[1, 3, 2, 3, 2],
        [4, 2, 1, 1, 3],
        [6, 3, 5, 1, 8],
        [4, 2, 8, 9, 2]]])

In [10]:
np.random.rand(2,2)

array([[0.06528956, 0.51887299],
       [0.95633979, 0.66329138]])

In [11]:
np.random.randn(2,2)

array([[ 1.05899572,  0.05798379],
       [-0.95943682, -0.31939777]])

In [12]:
a = np.arange(1,18)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [15]:
np.random.choice(a)

6